[workspace]
members = [
    "oathgate-net",
    "oathgate-vhost",
    "upstreams/udp-dummy"
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
rand = "0.8.5"
thiserror = "1.0.59"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
