[package]
name = "udp-dummy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
oathgate-net = { path = "../../oathgate-net/" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
